# Data processing

In [1]:
import numpy as np
import pandas

In [2]:
data_path = "../Data/"
features_path = data_path + "default_features/"
annotation_path = data_path + "annotations/"
filename = "2.csv"

In [3]:
feature = pandas.read_csv(features_path+filename, header=0, sep=';')

In [4]:
feature.shape

(91, 6670)

In [5]:
print(feature.columns)

Index(['frameTime', 'pcm_LOGenergy_sma_range', 'pcm_LOGenergy_sma_maxPos',
       'pcm_LOGenergy_sma_minPos', 'pcm_LOGenergy_sma_maxameandist',
       'pcm_LOGenergy_sma_minameandist', 'pcm_LOGenergy_sma_linregc1',
       'pcm_LOGenergy_sma_linregc2', 'pcm_LOGenergy_sma_linregerrA',
       'pcm_LOGenergy_sma_linregerrQ',
       ...
       'pcm_Mag_spectralMinPos_sma_de_de_meanPeakDist',
       'pcm_Mag_spectralMinPos_sma_de_de_peakMean',
       'pcm_Mag_spectralMinPos_sma_de_de_peakMeanMeanDist',
       'pcm_Mag_spectralMinPos_sma_de_de_amean',
       'pcm_Mag_spectralMinPos_sma_de_de_absmean',
       'pcm_Mag_spectralMinPos_sma_de_de_qmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nzabsmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nzqmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nzgmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nnz'],
      dtype='object', length=6670)


In [6]:
# some sampling seem to be needed here
# DON'T RUN THIS CELL MULTIPLE TIMES
import random
oN = len(feature.columns)
N = 1000 # keeping feature number
keeping_features = [random.randint(1,oN-1) for _ in range(N)]
print(keeping_features[:100])

textfile = open("keepingfeatures.txt", "w")
for element in keeping_features:
    textfile.write(str(element) + "\n")
textfile.close()

# ABANDONED: because danger of randomness

[3766, 4838, 5410, 3970, 157, 2432, 2753, 4936, 4279, 3727, 3014, 3462, 5478, 1762, 3637, 3137, 2220, 3070, 5650, 1077, 302, 5212, 1107, 602, 941, 3066, 1959, 313, 5093, 5805, 313, 1776, 5617, 1985, 5326, 3443, 2467, 5407, 1263, 5551, 1290, 1570, 5922, 5198, 4170, 5370, 6593, 3644, 3725, 5207, 2727, 4372, 2227, 816, 3601, 455, 2517, 2701, 1351, 40, 2266, 5641, 4640, 1547, 2061, 4778, 5152, 1185, 3696, 1483, 381, 2278, 932, 4657, 1994, 1301, 4872, 3538, 5649, 4597, 3523, 5417, 6579, 3333, 5304, 3648, 3567, 169, 371, 1123, 3462, 5413, 1523, 6250, 88, 5519, 5931, 3661, 1905, 1339]


In [7]:
def sample(df):
    # assume column[0] is the time frame, so always sample it
    columns = df.columns
    l = []
    for i in range(len(columns)):
        if i%8 != 0:
            l.append(columns[i])
    df.drop(columns = l, inplace=True)
sample(feature)
print(feature.columns)

Index(['frameTime', 'pcm_LOGenergy_sma_linregerrA',
       'pcm_LOGenergy_sma_variance', 'pcm_LOGenergy_sma_iqr2-3',
       'pcm_LOGenergy_sma_peakMeanMeanDist', 'mfcc_sma[0]_range',
       'mfcc_sma[0]_linregerrQ', 'mfcc_sma[0]_stddev', 'mfcc_sma[0]_iqr1-3',
       'mfcc_sma[0]_amean',
       ...
       'pcm_Mag_spectralMaxPos_sma_de_de_range',
       'pcm_Mag_spectralMaxPos_sma_de_de_linregerrQ',
       'pcm_Mag_spectralMaxPos_sma_de_de_stddev',
       'pcm_Mag_spectralMaxPos_sma_de_de_iqr1-3',
       'pcm_Mag_spectralMaxPos_sma_de_de_amean',
       'pcm_Mag_spectralMinPos_sma_de_de_maxPos',
       'pcm_Mag_spectralMinPos_sma_de_de_qregc1',
       'pcm_Mag_spectralMinPos_sma_de_de_skewness',
       'pcm_Mag_spectralMinPos_sma_de_de_percentile95.0',
       'pcm_Mag_spectralMinPos_sma_de_de_absmean'],
      dtype='object', length=834)


In [8]:
print(len(feature.columns))

834


## Chop
Only need 15s-30s, and 30s-45

In [9]:
feature.drop(index=feature.index[:30], axis=0, inplace=True)
feature

frameTime  pcm_LOGenergy_sma_linregerrA  pcm_LOGenergy_sma_variance  \
30       15.0                      0.347328                    0.295986   
31       15.5                      0.234017                    0.098474   
32       16.0                      0.420187                    0.260420   
33       16.5                      0.430718                    0.283668   
34       17.0                      0.298567                    0.233044   
..        ...                           ...                         ...   
86       43.0                      0.260795                    0.121646   
87       43.5                      0.261805                    0.150591   
88       44.0                      0.331910                    0.262564   
89       44.5                      0.328929                    0.268391   
90       45.0                      0.119853                    0.047121   

    pcm_LOGenergy_sma_iqr2-3  pcm_LOGenergy_sma_peakMeanMeanDist  \
30                  0.208083                           -0.174235   
31                  0.160624                            0.280944   
32                  0.475598                            0.935678   
33                  0.352799                            0.917704   
34                  0.149954                            0.479633   
..                       ...                                 ...   
86                  0.239769                            0.360335   
87                  0.147348                            0.252206   
88                  0.552317                            0.498695   
89                  0.393450                            0.680854   
90                  0.000000                            9.927737   

    mfcc_sma[0]_range  mfcc_sma[0]_linregerrQ  mfcc_sma[0]_stddev  \
30          13.392820                5.698980            4.111526   
31           9.590948                1.997184            1.698593   
32           7.684847                3.003247            1.860324   
33          11.487360                8.470845            2.910635   
34          10.370310                3.163281            1.981737   
..                ...                     ...                 ...   
86           8.439070                1.778856            1.564461   
87           7.752182                2.655881            1.635337   
88           8.804253                3.784436            2.058999   
89          11.805790                3.695544            3.086174   
90           3.379218                0.370394            0.675681   

    mfcc_sma[0]_iqr1-3  mfcc_sma[0]_amean  ...  \
30            5.507568          -8.462677  ...   
31            1.340685          -4.848685  ...   
32            2.853355          -6.712025  ...   
33            3.634847          -5.428717  ...   
34            1.675158          -5.644440  ...   
..                 ...                ...  ...   
86            1.241989          -6.529404  ...   
87            1.789851          -6.260051  ...   
88            1.624687          -7.383332  ...   
89            5.749134          -8.383580  ...   
90            0.000000          -7.745416  ...   

    pcm_Mag_spectralMaxPos_sma_de_de_range  \
30                                786.2466   
31                                345.4056   
32                                679.6089   
33                                582.8810   
34                               1290.9980   
..                                     ...   
86                                648.3716   
87                               1033.4880   
88                                728.9423   
89                                660.3638   
90                                  0.0000   

    pcm_Mag_spectralMaxPos_sma_de_de_linregerrQ  \
30                                 3.802078e+04   
31                                 7.649129e+03   
32                                 2.571456e+04   
33                                 1.614880e+04   
34                                 6.907948e+04 

In [10]:
def getVectors(feature):
    X1 = np.array([])
    for i in range(30):
        temp = np.array(feature.values.tolist()[i][1:])
        X1 = np.concatenate((X1, temp), axis=0)


    X2 = np.array([])
    for i in range(30,60):
        temp = np.array(feature.values.tolist()[i][1:])
        X2 = np.concatenate((X2, temp), axis=0)

    Xf = np.vstack((X1,X2))
    return Xf
print(getVectors(feature))

[[ 3.473275e-01  2.959855e-01  2.080832e-01 ... -3.887372e-02
   3.762014e+02  2.092814e+02]
 [ 4.676715e-01  3.456230e-01  3.175430e-01 ... -2.296642e-02
   4.322094e+02  2.310139e+02]]


In [11]:
# Now functionalize this whole process

def read(si):
    filename = str(si)+".csv"
    feature = pandas.read_csv(features_path+filename, header=0, sep=';')
    sample(feature)
    feature.drop(index=feature.index[:30], axis=0, inplace=True)
    return getVectors(feature)

read(3)

array([[1.014791e+00, 1.704258e+00, 4.694948e-01, ..., 1.627713e-01,
        4.559964e+02, 2.397517e+02],
       [8.253806e-01, 1.517216e+00, 1.059114e+00, ..., 5.617919e-01,
        5.556147e+02, 2.450340e+02]])

## Now handles the annotations

In [12]:
valence = pandas.read_csv(annotation_path+"valence_cont_average.csv", header=0, sep=',')

In [13]:
valence

song_id  sample_15000ms  sample_15500ms  sample_16000ms  sample_16500ms  \
0          2       -0.073341       -0.074662       -0.074078       -0.078155   
1          3       -0.189701       -0.187763       -0.183738       -0.188760   
2          4        0.154287        0.148063        0.146956        0.151180   
3          5        0.149054        0.148261        0.147370        0.146956   
4          7        0.342818        0.345193        0.332023        0.328888   
..       ...             ...             ...             ...             ...   
739      995       -0.425810       -0.424535       -0.424535       -0.426027   
740      996        0.370974        0.371163        0.371793        0.372174   
741      997        0.226997        0.239746        0.245814        0.235652   
742      999        0.177187        0.183137        0.183478        0.185465   
743     1000        0.336654        0.342793        0.349526        0.351463   

     sample_17000ms  sample_17500ms  sample_18000ms  sample_18500ms  \
0         -0.081589       -0.080875       -0.083612       -0.082146   
1         -0.193703       -0.190832       -0.189039       -0.197552   
2          0.135941        0.076832        0.084486        0.088514   
3          0.147857        0.146928        0.145652        0.145796   
4          0.327603        0.329013        0.327885        0.334824   
..              ...             ...             ...             ...   
739       -0.429752       -0.429038       -0.431057       -0.431491   
740        0.373515        0.372438        0.371940        0.373093   
741        0.229721        0.218383        0.215178        0.215493   
742        0.186417        0.192754        0.199522        0.202609   
743        0.365453        0.371982        0.368127        0.361209   

     sample_19000ms  ...  sample_40500ms  sample_41000ms  sample_41500ms  \
0         -0.081633  ...       -0.324848       -0.324682       -0.328113   
1         -0.202871  ...       -0.313982       -0.305432       -0.294849   
2          0.090945  ...        0.217566        0.218894        0.222273   
3          0.146421  ...        0.133478        0.133478        0.134290   
4          0.328449  ...        0.327612        0.330914        0.331320   
..              ...  ...             ...             ...             ...   
739       -0.431559  ...       -0.480014       -0.481890       -0.479330   
740        0.375734  ...        0.410748        0.417448        0.419337   
741        0.221297  ...        0.388394        0.397010        0.408303   
742        0.203099  ...        0.293478        0.293697        0.294348   
743        0.364837  ...        0.279793        0.276815        0.287792   

     sample_42000ms  sample_42500ms  sample_43000ms  sample_43500ms  \
0         -0.330134       -0.330135       -0.331165       -0.331769   
1         -0.282939       -0.276366       -0.279426       -0.278661   
2          0.190337        0.173085        0.174891        0.179883   
3          0.133556        0.134593        0.134348        0.133955   
4          0.301550        0.295277        0.295031        0.319244   
..              ...             ...             ...             ...   
739       -0.480833       -0.489299       -0.492164       -0.497108   
740        0.418004        0.422072        0.428280        0.446347   
741        0.415272        0.424451        0.418644        0.425890   
742        0.294348        0.294348        0.294940        0.296522   
743        0.288164        0.288580        0.289080        0.287102   

     sample_44000ms  sample_44500ms  sample_45000ms  
0         -0.334287       -0.333847       -0.334209  
1         -0.274246       -0.270161       -0.263900  
2          0.182709        0.179331        0.178671  
3          0.133478        0.133478        0.133478  
4          0.316518        0.321732        0.307598  
..              ...             ...             ...  
739       -0.499396       -0.501116       -0.50

In [18]:
GrandTotal = 100 # total number of songs we will consider
id_list = [int(valence.iloc[i]['song_id']) for i in range(GrandTotal)]
print(id_list)

[2, 3, 4, 5, 7, 8, 10, 12, 13, 17, 18, 19, 20, 21, 22, 24, 25, 31, 32, 35, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 62, 64, 65, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 96, 98, 99, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125]


In [26]:
y = np.array([0])
for i in id_list:
    valencepure = valence.loc[valence['song_id'] == i].values.tolist()[0][2:]
    firsthalf = valencepure[:30]
    valence1 = sum(firsthalf)/len(firsthalf)
    secondhalf = valencepure[30:]
    valence2 = sum(secondhalf)/len(secondhalf)
    valences = np.array([[valence1],[valence2]])
    y = np.vstack((y,valences))
y = np.delete(y, 0, axis=0)
print(y)

# !!!!!!!!!!! y is finished here

[[-1.32049492e-01]
 [-3.07669562e-01]
 [-2.33264360e-01]
 [-3.00917022e-01]
 [ 1.15910364e-01]
 [ 1.95320929e-01]
 [ 1.47584115e-01]
 [ 1.32216952e-01]
 [ 3.38597327e-01]
 [ 3.25140005e-01]
 [-9.16989611e-03]
 [ 3.25285925e-03]
 [ 9.01067395e-02]
 [-7.13672013e-03]
 [ 3.38301654e-01]
 [ 3.45565148e-01]
 [-2.24327158e-01]
 [-2.31872301e-01]
 [ 1.60520252e-01]
 [ 1.81957525e-01]
 [ 2.44748236e-02]
 [-1.11250877e-01]
 [ 3.19045566e-02]
 [-5.31764552e-02]
 [ 3.35905462e-01]
 [ 3.39875200e-01]
 [ 3.31121844e-01]
 [ 3.31599506e-01]
 [ 1.54315324e-02]
 [ 1.48612285e-02]
 [-2.74405101e-02]
 [-1.07845564e-01]
 [-2.70104197e-01]
 [-1.74747733e-01]
 [-1.81334730e-01]
 [-1.80261448e-01]
 [-1.37341698e-01]
 [-2.07310713e-01]
 [ 3.58419731e-01]
 [ 4.09877830e-01]
 [ 2.62162104e-01]
 [ 2.71115715e-01]
 [ 1.59276765e-01]
 [ 1.62035899e-01]
 [ 3.15363538e-02]
 [ 1.18050490e-01]
 [-5.98148299e-02]
 [-1.10682478e-01]
 [ 1.32957341e-02]
 [-9.32252210e-03]
 [-1.15098564e-01]
 [-2.16952537e-01]
 [-1.4618964

In [27]:
y.shape

(200, 1)

## Now load features of all relevant music

In [20]:
x = read(id_list[0])
for i in id_list[1:]:
    x = np.vstack((x, read(i)))
print(x)

[[ 3.473275e-01  2.959855e-01  2.080832e-01 ... -3.887372e-02
   3.762014e+02  2.092814e+02]
 [ 4.676715e-01  3.456230e-01  3.175430e-01 ... -2.296642e-02
   4.322094e+02  2.310139e+02]
 [ 1.014791e+00  1.704258e+00  4.694948e-01 ...  1.627713e-01
   4.559964e+02  2.397517e+02]
 ...
 [ 3.994412e-01  7.264205e-01  9.585667e-02 ...  2.681313e-01
   3.918594e+02  2.029951e+02]
 [ 8.379098e-01  1.404955e+00  5.991759e-01 ...  1.373305e-01
   4.504239e+02  2.165715e+02]
 [ 7.709534e-01  1.536961e+00  2.340627e-01 ...  3.705721e-01
   6.646939e+02  2.986847e+02]]


In [24]:
x.shape

(200, 24990)

# Machine Learning begins here

In [32]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge

In [30]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=23)

In [31]:
X_train

array([[ 3.397585e-01,  2.612214e-01,  1.839609e-01, ...,  7.770327e-02,
         5.314722e+02,  2.834739e+02],
       [ 1.574016e+00,  3.696115e+00,  2.132308e+00, ..., -8.667718e-03,
         2.581494e+02,  1.325653e+02],
       [ 7.194723e-01,  7.504091e-01,  7.828417e-01, ..., -5.364980e-01,
         1.512782e+02,  9.547987e+01],
       ...,
       [ 8.849841e-01,  1.757580e+00,  3.320236e-01, ...,  7.090234e-01,
         6.608521e+02,  3.079510e+02],
       [ 5.931537e-01,  5.196922e-01,  9.340363e-01, ...,  2.177742e-01,
         7.765091e+02,  3.617036e+02],
       [ 1.943565e-01,  7.630416e-02,  1.650934e-01, ..., -5.365925e-01,
         3.326378e+02,  1.749059e+02]])

In [37]:
reg = Ridge()
reg.fit(X_train,y_train)

print("Ridge Regression")
print("Training Score",reg.score(X_train, y_train))
print("Testing Score",reg.score(X_test, y_test))
np.savetxt("coef.csv", reg.coef_, delimiter=",")

Ridge Regression
Training Score 1.0
Testing Score -158.89530986401044


/usr/local/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "


In [38]:
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor

In [40]:
ada = AdaBoostRegressor()
ada.fit(X_train, y_train.ravel())

AdaBoostRegressor()

In [42]:
print("Ada Boost")
print("Training Score",ada.score(X_train, y_train.ravel()))
print("Testing Score",ada.score(X_test, y_test.ravel()))

Ada Boost
Training Score 0.9285369783814101
Testing Score 0.16601788197153833


## I want to test the classification accuracy

In [61]:
print(y_train)

[[-0.16684294]
 [ 0.30140308]
 [ 0.11805049]
 [ 0.00513606]
 [-0.21102741]
 [ 0.16412698]
 [ 0.14985357]
 [-0.12203901]
 [-0.02576014]
 [ 0.55813282]
 [ 0.30156804]
 [ 0.26366069]
 [ 0.1808255 ]
 [ 0.026213  ]
 [ 0.0470391 ]
 [-0.16219568]
 [-0.36929269]
 [ 0.19537943]
 [ 0.00140541]
 [-0.24018243]
 [-0.23326436]
 [-0.38529468]
 [-0.09836896]
 [ 0.25902057]
 [-0.05195435]
 [ 0.14638313]
 [ 0.09394211]
 [ 0.32514   ]
 [-0.22432716]
 [ 0.02777451]
 [ 0.13221695]
 [ 0.19532093]
 [-0.30683124]
 [-0.04642276]
 [-0.14626925]
 [-0.28093813]
 [ 0.13649565]
 [-0.47588754]
 [ 0.1310293 ]
 [-0.21890889]
 [ 0.34093677]
 [-0.23636615]
 [-0.02969003]
 [ 0.15092294]
 [ 0.09234232]
 [-0.00582966]
 [-0.18133473]
 [-0.22197585]
 [ 0.28446557]
 [-0.08517229]
 [-0.17474773]
 [-0.4377091 ]
 [-0.23728839]
 [-0.11509856]
 [-0.01907389]
 [ 0.03506461]
 [ 0.11591036]
 [ 0.35841973]
 [ 0.15927676]
 [ 0.01486123]
 [-0.26771979]
 [-0.05317646]
 [-0.14158846]
 [ 0.26268875]
 [-0.11161053]
 [-0.20731071]
 [ 0.33112

In [75]:
def accuracy(model, X, y):
    yp = model.predict(X) # model prediction
    correct_num = 0
    n = len(y)
    if len(yp)>1:
        yp = yp.reshape(len(yp),1)
    for i in range(n):
        if yp[i][0] * y[i][0] > 0:
            correct_num +=1
    return correct_num/n
    

In [77]:
accuracy(ada,X_test, y_)

0.9552238805970149

134
