# Data processing

In [1]:
import numpy as np
import pandas

In [2]:
data_path = "../Data/"
features_path = data_path + "default_features/"
annotation_path = data_path + "annotations/"
filename = "2.csv"

In [3]:
feature = pandas.read_csv(features_path+filename, header=0, sep=';')

In [4]:
feature.shape

(91, 6670)

In [5]:
print(feature.columns)

Index(['frameTime', 'pcm_LOGenergy_sma_range', 'pcm_LOGenergy_sma_maxPos',
       'pcm_LOGenergy_sma_minPos', 'pcm_LOGenergy_sma_maxameandist',
       'pcm_LOGenergy_sma_minameandist', 'pcm_LOGenergy_sma_linregc1',
       'pcm_LOGenergy_sma_linregc2', 'pcm_LOGenergy_sma_linregerrA',
       'pcm_LOGenergy_sma_linregerrQ',
       ...
       'pcm_Mag_spectralMinPos_sma_de_de_meanPeakDist',
       'pcm_Mag_spectralMinPos_sma_de_de_peakMean',
       'pcm_Mag_spectralMinPos_sma_de_de_peakMeanMeanDist',
       'pcm_Mag_spectralMinPos_sma_de_de_amean',
       'pcm_Mag_spectralMinPos_sma_de_de_absmean',
       'pcm_Mag_spectralMinPos_sma_de_de_qmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nzabsmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nzqmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nzgmean',
       'pcm_Mag_spectralMinPos_sma_de_de_nnz'],
      dtype='object', length=6670)


In [6]:
# some sampling seem to be needed here
# DON'T RUN THIS CELL MULTIPLE TIMES
import random
oN = len(feature.columns)
N = 1000 # keeping feature number
keeping_features = [random.randint(1,oN-1) for _ in range(N)]
print(keeping_features[:100])

textfile = open("keepingfeatures.txt", "w")
for element in keeping_features:
    textfile.write(str(element) + "\n")
textfile.close()

# ABANDONED: because danger of randomness

[2902, 3048, 6208, 4587, 2671, 5319, 2416, 2932, 3217, 5866, 2317, 5954, 6181, 5328, 1673, 5218, 3413, 3825, 405, 5258, 6421, 2673, 3537, 3475, 6105, 4615, 1839, 5672, 1523, 1677, 2310, 4342, 4733, 2970, 3365, 6008, 2537, 6413, 411, 3995, 5009, 55, 3863, 6042, 6333, 6237, 5794, 1500, 5180, 1755, 2015, 2242, 6602, 398, 3900, 1582, 1449, 1677, 2451, 5348, 4018, 3269, 1165, 5208, 2251, 2642, 6573, 2021, 1018, 3113, 3984, 3594, 2114, 6266, 5169, 1966, 4781, 2432, 6081, 1690, 3837, 1146, 11, 813, 1688, 329, 3841, 5165, 3477, 1941, 2917, 3700, 205, 4923, 3204, 2442, 501, 748, 2338, 2494]


In [7]:
def sample(df):
    # assume column[0] is the time frame, so always sample it
    columns = df.columns
    l = []
    for i in range(len(columns)):
        if i%8 != 0:
            l.append(columns[i])
    df.drop(columns = l, inplace=True)
sample(feature)
print(feature.columns)

Index(['frameTime', 'pcm_LOGenergy_sma_linregerrA',
       'pcm_LOGenergy_sma_variance', 'pcm_LOGenergy_sma_iqr2-3',
       'pcm_LOGenergy_sma_peakMeanMeanDist', 'mfcc_sma[0]_range',
       'mfcc_sma[0]_linregerrQ', 'mfcc_sma[0]_stddev', 'mfcc_sma[0]_iqr1-3',
       'mfcc_sma[0]_amean',
       ...
       'pcm_Mag_spectralMaxPos_sma_de_de_range',
       'pcm_Mag_spectralMaxPos_sma_de_de_linregerrQ',
       'pcm_Mag_spectralMaxPos_sma_de_de_stddev',
       'pcm_Mag_spectralMaxPos_sma_de_de_iqr1-3',
       'pcm_Mag_spectralMaxPos_sma_de_de_amean',
       'pcm_Mag_spectralMinPos_sma_de_de_maxPos',
       'pcm_Mag_spectralMinPos_sma_de_de_qregc1',
       'pcm_Mag_spectralMinPos_sma_de_de_skewness',
       'pcm_Mag_spectralMinPos_sma_de_de_percentile95.0',
       'pcm_Mag_spectralMinPos_sma_de_de_absmean'],
      dtype='object', length=834)


In [8]:
print(len(feature.columns))

834


## Chop
Only need 15s-30s, and 30s-45

In [9]:
feature.drop(index=feature.index[:30], axis=0, inplace=True)
feature

frameTime  pcm_LOGenergy_sma_linregerrA  pcm_LOGenergy_sma_variance  \
30       15.0                      0.347328                    0.295986   
31       15.5                      0.234017                    0.098474   
32       16.0                      0.420187                    0.260420   
33       16.5                      0.430718                    0.283668   
34       17.0                      0.298567                    0.233044   
..        ...                           ...                         ...   
86       43.0                      0.260795                    0.121646   
87       43.5                      0.261805                    0.150591   
88       44.0                      0.331910                    0.262564   
89       44.5                      0.328929                    0.268391   
90       45.0                      0.119853                    0.047121   

    pcm_LOGenergy_sma_iqr2-3  pcm_LOGenergy_sma_peakMeanMeanDist  \
30                  0.208083                           -0.174235   
31                  0.160624                            0.280944   
32                  0.475598                            0.935678   
33                  0.352799                            0.917704   
34                  0.149954                            0.479633   
..                       ...                                 ...   
86                  0.239769                            0.360335   
87                  0.147348                            0.252206   
88                  0.552317                            0.498695   
89                  0.393450                            0.680854   
90                  0.000000                            9.927737   

    mfcc_sma[0]_range  mfcc_sma[0]_linregerrQ  mfcc_sma[0]_stddev  \
30          13.392820                5.698980            4.111526   
31           9.590948                1.997184            1.698593   
32           7.684847                3.003247            1.860324   
33          11.487360                8.470845            2.910635   
34          10.370310                3.163281            1.981737   
..                ...                     ...                 ...   
86           8.439070                1.778856            1.564461   
87           7.752182                2.655881            1.635337   
88           8.804253                3.784436            2.058999   
89          11.805790                3.695544            3.086174   
90           3.379218                0.370394            0.675681   

    mfcc_sma[0]_iqr1-3  mfcc_sma[0]_amean  ...  \
30            5.507568          -8.462677  ...   
31            1.340685          -4.848685  ...   
32            2.853355          -6.712025  ...   
33            3.634847          -5.428717  ...   
34            1.675158          -5.644440  ...   
..                 ...                ...  ...   
86            1.241989          -6.529404  ...   
87            1.789851          -6.260051  ...   
88            1.624687          -7.383332  ...   
89            5.749134          -8.383580  ...   
90            0.000000          -7.745416  ...   

    pcm_Mag_spectralMaxPos_sma_de_de_range  \
30                                786.2466   
31                                345.4056   
32                                679.6089   
33                                582.8810   
34                               1290.9980   
..                                     ...   
86                                648.3716   
87                               1033.4880   
88                                728.9423   
89                                660.3638   
90                                  0.0000   

    pcm_Mag_spectralMaxPos_sma_de_de_linregerrQ  \
30                                 3.802078e+04   
31                                 7.649129e+03   
32                                 2.571456e+04   
33                                 1.614880e+04   
34                                 6.907948e+04 

In [10]:
def getVectors(feature):
    X1 = np.array([])
    for i in range(30):
        temp = np.array(feature.values.tolist()[i][1:])
        X1 = np.concatenate((X1, temp), axis=0)


    X2 = np.array([])
    for i in range(30,60):
        temp = np.array(feature.values.tolist()[i][1:])
        X2 = np.concatenate((X2, temp), axis=0)

    Xf = np.vstack((X1,X2))
    return Xf
print(getVectors(feature))

[[ 3.473275e-01  2.959855e-01  2.080832e-01 ... -3.887372e-02
   3.762014e+02  2.092814e+02]
 [ 4.676715e-01  3.456230e-01  3.175430e-01 ... -2.296642e-02
   4.322094e+02  2.310139e+02]]


In [11]:
# Now functionalize this whole process

def read(si):
    filename = str(si)+".csv"
    feature = pandas.read_csv(features_path+filename, header=0, sep=';')
    sample(feature)
    feature.drop(index=feature.index[:30], axis=0, inplace=True)
    return getVectors(feature)

read(3)

array([[1.014791e+00, 1.704258e+00, 4.694948e-01, ..., 1.627713e-01,
        4.559964e+02, 2.397517e+02],
       [8.253806e-01, 1.517216e+00, 1.059114e+00, ..., 5.617919e-01,
        5.556147e+02, 2.450340e+02]])

## Now handles the annotations

In [12]:
valence = pandas.read_csv(annotation_path+"arousal_cont_average.csv", header=0, sep=',')

In [13]:
valence

song_id  sample_15000ms  sample_15500ms  sample_16000ms  sample_16500ms  \
0          2       -0.109388       -0.114943       -0.116414       -0.118614   
1          3       -0.110847       -0.123974       -0.131104       -0.135957   
2          4        0.222328        0.179448        0.178389        0.184057   
3          5       -0.255613       -0.251578       -0.251957       -0.251123   
4          7        0.464233        0.460788        0.460990        0.461046   
..       ...             ...             ...             ...             ...   
739      995       -0.083658       -0.079965       -0.080614       -0.077533   
740      996        0.340385        0.339627        0.340270        0.335955   
741      997        0.367088        0.368839        0.352861        0.311679   
742      999       -0.176851       -0.173603       -0.179410       -0.171693   
743     1000        0.432808        0.434732        0.440664        0.446552   

     sample_17000ms  sample_17500ms  sample_18000ms  sample_18500ms  \
0         -0.126458       -0.133200       -0.136857       -0.144714   
1         -0.140777       -0.144664       -0.163118       -0.165218   
2          0.176043        0.178720        0.176345        0.175793   
3         -0.250762       -0.251957       -0.251957       -0.251957   
4          0.457239        0.465701        0.471808        0.469918   
..              ...             ...             ...             ...   
739       -0.081066       -0.082564       -0.075276       -0.071917   
740        0.338222        0.335331        0.340030        0.343517   
741        0.278800        0.253148        0.249393        0.243813   
742       -0.167945       -0.162917       -0.163924       -0.164752   
743        0.444164        0.462809        0.441230        0.440520   

     sample_19000ms  ...  sample_40500ms  sample_41000ms  sample_41500ms  \
0         -0.138987  ...       -0.259550       -0.262237       -0.261481   
1         -0.158859  ...       -0.265929       -0.263960       -0.263571   
2          0.176155  ...        0.298644        0.294144        0.302703   
3         -0.251957  ...       -0.225898       -0.228913       -0.228913   
4          0.473376  ...        0.333163        0.331243        0.333927   
..              ...  ...             ...             ...             ...   
739       -0.072352  ...       -0.046469       -0.044649       -0.041990   
740        0.347987  ...        0.364017        0.366737        0.366231   
741        0.238716  ...        0.257732        0.293368        0.312197   
742       -0.168172  ...       -0.156017       -0.155395       -0.158082   
743        0.440478  ...        0.498058        0.495228        0.495945   

     sample_42000ms  sample_42500ms  sample_43000ms  sample_43500ms  \
0         -0.264916       -0.265397       -0.265162       -0.264470   
1         -0.262956       -0.260337       -0.248710       -0.245516   
2          0.297487        0.303424        0.298097        0.304340   
3         -0.228913       -0.228913       -0.227561       -0.227609   
4          0.333740        0.340782        0.339002        0.339271   
..              ...             ...             ...             ...   
739       -0.035563       -0.037822       -0.040367       -0.043850   
740        0.366730        0.365032        0.366610        0.367975   
741        0.327872        0.337830        0.332809        0.332175   
742       -0.158439       -0.154866       -0.155621       -0.155486   
743        0.494470        0.494153        0.495761        0.496498   

     sample_44000ms  sample_44500ms  sample_45000ms  
0         -0.265842       -0.267091       -0.266345  
1         -0.251299       -0.254619       -0.259586  
2          0.304115        0.305079        0.290705  
3         -0.229996       -0.243920       -0.246009  
4          0.340961        0.342020        0.335976  
..              ...             ...             ...  
739       -0.049861       -0.046132       -0.05

In [14]:
GrandTotal = 300 # total number of songs we will consider
id_list = [int(valence.iloc[i]['song_id']) for i in range(GrandTotal)]
print(id_list)

[2, 3, 4, 5, 7, 8, 10, 12, 13, 17, 18, 19, 20, 21, 22, 24, 25, 31, 32, 35, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 62, 64, 65, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 96, 98, 99, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 135, 136, 137, 138, 140, 142, 143, 144, 145, 146, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 250, 

In [15]:
y = np.array([0])
for i in id_list:
    valencepure = valence.loc[valence['song_id'] == i].values.tolist()[0][2:]
    firsthalf = valencepure[:30]
    valence1 = sum(firsthalf)/len(firsthalf)
    secondhalf = valencepure[30:]
    valence2 = sum(secondhalf)/len(secondhalf)
    valences = np.array([[valence1],[valence2]])
    y = np.vstack((y,valences))
y = np.delete(y, 0, axis=0)
print(y)

# !!!!!!!!!!! y is finished here

[[-1.43896204e-01]
 [-2.56373636e-01]
 [-1.60904782e-01]
 [-2.30427709e-01]
 [ 1.94382968e-01]
 [ 2.94042085e-01]
 [-2.41904960e-01]
 [-2.30187606e-01]
 [ 4.14635263e-01]
 [ 3.33673404e-01]
 [-1.32275133e-01]
 [-1.31738991e-01]
 [-1.64464319e-01]
 [-1.79355446e-01]
 [ 2.60439253e-01]
 [ 3.14752794e-01]
 [-3.33365591e-01]
 [-3.23985970e-01]
 [ 1.74670509e-02]
 [ 4.53411163e-02]
 [-1.72182087e-01]
 [-1.26429671e-01]
 [ 2.87312503e-01]
 [ 2.72676623e-01]
 [ 4.41892557e-02]
 [ 4.12862898e-02]
 [ 3.87348909e-01]
 [ 3.97311592e-01]
 [-1.58203862e-01]
 [-1.65912842e-01]
 [ 9.12565727e-02]
 [ 1.47893852e-01]
 [ 5.49680850e-01]
 [ 5.31639500e-01]
 [ 7.85160298e-02]
 [ 7.24718728e-02]
 [-3.20643226e-02]
 [-2.10883595e-02]
 [ 2.66671343e-02]
 [-2.36961441e-02]
 [ 3.56328202e-01]
 [ 3.80999991e-01]
 [ 5.67435699e-01]
 [ 6.12875222e-01]
 [-2.91383666e-01]
 [-1.54259634e-01]
 [-1.53908009e-01]
 [-1.94084720e-01]
 [ 3.05581404e-01]
 [ 3.06158460e-01]
 [ 4.05627215e-01]
 [ 4.24410844e-01]
 [-2.8338052

In [16]:
y.shape

(600, 1)

## Now load features of all relevant music

In [17]:
x = read(id_list[0])
for i in id_list[1:]:
    x = np.vstack((x, read(i)))
print(x)

[[ 3.473275e-01  2.959855e-01  2.080832e-01 ... -3.887372e-02
   3.762014e+02  2.092814e+02]
 [ 4.676715e-01  3.456230e-01  3.175430e-01 ... -2.296642e-02
   4.322094e+02  2.310139e+02]
 [ 1.014791e+00  1.704258e+00  4.694948e-01 ...  1.627713e-01
   4.559964e+02  2.397517e+02]
 ...
 [ 8.338575e-01  1.057412e+00  6.819048e-01 ...  8.346831e-01
   9.754333e+02  4.245343e+02]
 [ 1.377586e+00  3.942015e+00  1.714334e+00 ...  5.076049e-01
   6.214356e+02  2.701732e+02]
 [ 4.599538e-01  2.406640e+00  2.556315e+00 ...  9.739859e-02
   6.405012e+02  3.563724e+02]]


In [18]:
x.shape

(600, 24990)

# Machine Learning begins here

In [19]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=23)

In [21]:
X_train

array([[ 2.545171e-01,  1.412327e-01,  4.186449e-01, ..., -4.609228e-02,
         6.548201e+02,  3.327685e+02],
       [ 3.152011e-01,  1.744199e-01,  2.578692e-01, ..., -9.339549e-02,
         5.459778e+02,  3.844314e+02],
       [ 5.848761e-01,  5.116886e-01,  5.768600e-01, ..., -1.807785e-02,
         3.774077e+02,  1.967749e+02],
       ...,
       [ 7.233829e-01,  7.895511e-01,  8.594646e-01, ..., -1.336480e-01,
         4.735395e+02,  2.143669e+02],
       [ 5.931537e-01,  5.196922e-01,  9.340363e-01, ...,  2.177742e-01,
         7.765091e+02,  3.617036e+02],
       [ 2.660848e-01,  1.357212e-01,  3.986416e-01, ..., -2.408668e-01,
         4.609477e+02,  2.299697e+02]])

In [22]:
reg = Ridge()
reg.fit(X_train,y_train)

print("Ridge Regression")
print("Training Score",reg.score(X_train, y_train))
print("Testing Score",reg.score(X_test, y_test))
np.savetxt("coef.csv", reg.coef_, delimiter=",")

Ridge Regression
Training Score 0.9999999999999992
Testing Score -2487.9011777749524


/usr/local/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "


In [23]:
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor

In [24]:
ada = AdaBoostRegressor()
ada.fit(X_train, y_train.ravel())

AdaBoostRegressor()

In [25]:
print("Ada Boost")
print("Training Score",ada.score(X_train, y_train.ravel()))
print("Testing Score",ada.score(X_test, y_test.ravel()))

Ada Boost
Training Score 0.8791203921475956
Testing Score 0.6104939531819231


## I want to test the classification accuracy

In [26]:
print(y_train)

[[-0.35177324]
 [ 0.63742536]
 [ 0.01746705]
 [ 0.50694333]
 [-0.48153166]
 [ 0.63452483]
 [-0.33336559]
 [-0.10375518]
 [-0.10676415]
 [ 0.4724739 ]
 [ 0.29793449]
 [-0.26681911]
 [-0.03060944]
 [-0.22472386]
 [-0.17935545]
 [ 0.02666713]
 [-0.19583221]
 [-0.21159264]
 [ 0.25132076]
 [ 0.01962957]
 [-0.48349678]
 [ 0.15688621]
 [ 0.5316395 ]
 [ 0.08056244]
 [-0.12810059]
 [ 0.02089365]
 [-0.38550983]
 [-0.33237542]
 [-0.2086527 ]
 [-0.02148444]
 [-0.15779637]
 [ 0.55058091]
 [-0.20776819]
 [-0.03206432]
 [ 0.02365418]
 [-0.5723497 ]
 [-0.3632572 ]
 [ 0.15532978]
 [-0.55212769]
 [ 0.00750871]
 [-0.25016268]
 [ 0.36322075]
 [-0.28515594]
 [ 0.40562722]
 [-0.27764968]
 [-0.1862592 ]
 [-0.36224087]
 [-0.1589136 ]
 [ 0.34713081]
 [ 0.38734891]
 [ 0.2426074 ]
 [ 0.14583717]
 [-0.06351189]
 [-0.26503992]
 [ 0.35834668]
 [ 0.23739383]
 [-0.16333948]
 [-0.24622377]
 [ 0.4158476 ]
 [ 0.19248507]
 [ 0.27793106]
 [ 0.29404208]
 [-0.11288254]
 [-0.16090478]
 [-0.23264179]
 [ 0.3320645 ]
 [-0.25715

In [27]:
def accuracy(model, X, y):
    yp = model.predict(X) # model prediction
    correct_num = 0
    n = len(y)
    if len(yp)>1:
        yp = yp.reshape(len(yp),1)
    for i in range(n):
        if yp[i][0] * y[i][0] > 0:
            correct_num +=1
    return correct_num/n
    

In [28]:
accuracy(ada,X_test, y_test)

0.803030303030303

In [29]:
accuracy(reg,X_test, y_test)

0.48484848484848486

# Now I want to save the model for future use

In [30]:
from joblib import dump, load
dump(ada, 'ada2.joblib') 

['ada2.joblib']

In [31]:
bdb = load('ada2.joblib') 

In [32]:
accuracy(bdb,X_test, y_test)

0.803030303030303

## Doc: to use the model stored in ada.joblib
from joblib import dump, load

from sklearn.ensemble import AdaBoostRegressor

ada = load('ada.joblib') 

ada.predict(X)